admin-openrc:
  OS_PROJECT_DOMAIN_NAME: Default
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: admin
  OS_USERNAME: admin
  OS_PASSWORD: "{{ADMIN_PASS}}"
  OS_AUTH_URL: http://controller:35357/v3
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2
demo-openrc:
  OS_PROJECT_DOMAIN_NAME: Default
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: demo
  OS_USERNAME: demo
  OS_PASSWORD: "{{DEMO_PASS}}"
  OS_AUTH_URL: http://controller:5000/v3
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2


