---
- name: Drop DB glance if exists
  command: mysql --execute="DROP DATABASE IF EXISTS glance"
- name: Create DB for Glance
  command: mysql --execute="CREATE DATABASE glance"  
- name: Grant proper access to glance database
  command: mysql --execute="{{item}}"
  with_items: 
    - GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost'  IDENTIFIED BY '{{GLANCE_DBPASS}}';
    - GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%'  IDENTIFIED BY '{{GLANCE_DBPASS}}';
# - name: Delete glance user
#   command: openstack user delete --domain default glance
#   environment:
#     OS_PROJECT_DOMAIN_NAME: Default
#     OS_USER_DOMAIN_NAME: Default
#     OS_PROJECT_NAME: admin
#     OS_USERNAME: admin
#     OS_PASSWORD: "{{ADMIN_PASS}}"
#     OS_AUTH_URL: http://controller:35357/v3
#     OS_IDENTITY_API_VERSION: 3
#     OS_IMAGE_API_VERSION: 2    
- name: Create glance user
  command: openstack user create --domain default --password "{{GLANCE_DBPASS}}" glance
  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ADMIN_PASS}}"
    OS_AUTH_URL: http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
- name: Add role to glance user and service project
  command: openstack role add --project service --user glance admin
  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ADMIN_PASS}}"
    OS_AUTH_URL: http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
- name: Create glance service entity  
  command: openstack service create --name glance  --description "OpenStack Image" image
  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ADMIN_PASS}}"
    OS_AUTH_URL: http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
- name: Create endpoint for glance service
  command: "{{item}}"
  with_items:
#     - openstack endpoint delete --region RegionOne  image public http://controller:9292
#     - openstack endpoint delete --region RegionOne   image internal http://controller:9292
#     - openstack endpoint delete --region RegionOne  image admin http://controller:9292
    - openstack endpoint create --region RegionOne  image public http://controller:9292
    - openstack endpoint create --region RegionOne   image internal http://controller:9292
    - openstack endpoint create --region RegionOne  image admin http://controller:9292
  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ADMIN_PASS}}"
    OS_AUTH_URL: http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
- name: Install package
  apt:
    name: glance
    state: present
- name: Edit glance-api.conf
  ini_file:
    path: /etc/glance/glance-api.conf
    section: database
    option: connection
    value: mysql+pymysql://glance:{{ GLANCE_DBPASS }}@controller/glance
    backup: yes
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: auth_uri
    value: http://controller:5000
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: auth_url
    value: http://controller:35357
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: memcached_servers
    value: controller:11211
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: auth_type
    value: password
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: project_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: user_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: project_name
    value: service
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: username
    value: glance
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: keystone_authtoken
    option: password
    value: "{{GLANCE_DBPASS}}"
- name: Edit paste_deploy
  ini_file:
    path: /etc/glance/glance-api.conf
    section: paste_deploy
    option: flavor
    value: keystone
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: glance_store
    option: stores
    value: file,http
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: glance_store
    option: default_store
    value: file
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-api.conf
    section: glance_store
    option: filesystem_store_datadir
    value: /var/lib/glance/images/
- name: Edit glance-registry.conf
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: database
    option: connection
    value: mysql+pymysql://glance:{{GLANCE_DBPASS}}@controller/glance
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: auth_uri
    value: http://controller:5000
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: auth_url
    value: http://controller:35357
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: memcached_servers
    value: controller:11211
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: auth_type
    value: password
- name: Edit continue
  ini_file: 
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: project_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: user_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: project_name
    value: service
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: username
    value: glance
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: keystone_authtoken
    option: password
    value: "{{GLANCE_DBPASS}}"
- name: Edit continue
  ini_file:
    path: /etc/glance/glance-registry.conf
    section: paste_deploy
    option: flavor
    value: keystone 
- name: Populate Image service database
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  notify:
    - restart glance-registry
    - restart glance-api
