---
- name: Install components
  apt:
    name: neutron-linuxbridge-agent
    state: present
- name: Configure common component
  ini_file:
    path: /etc/neutron/neutron.conf
    section: database
    option: connection
    state: absent
    backup: yes
- name: Configure Default section
  ini_file:
    path: /etc/neutron/neutron.conf
    section: DEFAULT
    option: transport_url
    value: rabbit://openstack:{{ RABBIT_PASS }}@controller
- name: Config continue
  ini_file:
    path: /etc/neutron/neutron.conf
    section: DEFAULT
    option: auth_strategy
    value: keystone
- name: Configure keystone_authtoken
  ini_file:
    path: /etc/neutron/neutron.conf
    section: keystone_authtoken
    value: |
      auth_uri = http://controller:5000
      auth_url = http://controller:35357
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = neutron
      password = {{ NEUTRON_PASS }}
- name: Configure Linux bridge agent
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: linux_bridge
    option: physical_interface_mappings
    value: provider:{{ PROVIDER_INTERFACE_NAME }}
    backup: yes
- name: Configure vxlan section
  ini_file: 
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: vxlan
    option: enable_vxlan 
    value: true
- name: Configure vxlan section
  ini_file: 
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: vxlan
    option: local_ip
    value: "{{ OVERLAY_INTERFACE_IP_ADDRESS }}"
- name: Configure vxlan section
  ini_file: 
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: vxlan
    option: l2_population
    value: true
- name: Configure vxlan securitygroup
  ini_file: 
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: securitygroup
    option: enable_security_group
    value: true
- name: Configure vxlan securitygroup
  ini_file: 
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: securitygroup
    option: firewall_driver
    value: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
- name: Configure Compute service to use Networking service 
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: url
    value: http://controller:9696
    backup: yes
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: auth_url
    value: http://controller:35357
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: auth_type
    value: password
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: project_domain_name
    value: default
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: user_domain_name
    value: default
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: region_name
    value: RegionOne
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: project_name
    value: service
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: username
    value: neutron
- name: Configure continue
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: password
    value: "{{ NEUTRON_PASS }}"
- name: Finalize installation
  command: "{{ item }}"
  with_items:
    - service nova-compute restart
    - service neutron-linuxbridge-agent restart
