---
- name: Install package
  apt: 
    name: nova-compute
    state: present
- name: Edit /etc/nova/nova.conf
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: transport_url
    value: rabbit://openstack:{{ RABBIT_PASS }}@controller
    backup: yes 
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: api
    option: auth_strategy
    value: keystone
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: auth_uri
    value: http://controller:5000
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: auth_url
    value: http://controller:35357
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: memcached_servers
    value: controller:11211
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: auth_type
    value: password
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: project_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: user_domain_name
    value: default
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: project_name
    value: service
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: username
    value: nova
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: keystone_authtoken
    option: password
    value: "{{ NOVA_PASS }}"
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: my_ip
    value: "{{ MANAGEMENT_IP }}"
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: use_neutron
    value: True
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: firewall_driver
    value: nova.virt.firewall.NoopFirewallDriver
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: vnc
    option: enabled
    value: True
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: vnc
    option: vncserver_listen
    value: 0.0.0.0
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: vnc
    option: vncserver_proxyclient_address
    value: $my_ip
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: vnc
    option: novncproxy_base_url
    value: http://controller:6080/vnc_auto.html
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: glance
    option: api_servers
    value: http://controller:9292
- name: Edit continue
  ini_file:
    path: /etc/nova/nova.conf
    section: oslo_concurrency
    option: lock_path
    value: /var/lib/nova/tmp
- name: Remove log_dir
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: log_dir 
    state: absent
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: os_region_name
    value: RegionOne
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: project_domain_name
    value: Default
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: project_name
    value: service
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: auth_type
    value: password
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: user_domain_name
    value: Default
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: auth_url
    value: http://controller:35357/v3
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: username
    value: placement
- name: Configure Placement API
  ini_file:
    path: /etc/nova/nova.conf
    section: placement
    option: password
    value: "{{ PLACEMENT_PASS }}"
- name: Determine whether your compute node support hardware acceleration for VM
  shell: cpu="$(egrep -c '(vmx|svm)' /proc/cpuinfo)"
  register: cpu
  ignore_errors: True
- name: Config based cpu
  ini_file:
    path: /etc/nova/nova-compute.conf
    section: libvirt
    option: virt_type
    value: qemu
  when: cpu.stdout == 0
  notify: restart nova-compute

